# I2C
snd-soc-tasdevice-objs	:= \
	tasdevice-regbin.o \
	tasdevice-core.o \
	tasdevice-node.o \
	tasdevice-rw.o  \
	tas2780-irq.o	\
	tas2770-irq.o \
	tas2560-irq.o	\
	tas2564-irq.o	\
	tas257x-irq.o	\
	pcm9211-irq.o
obj-$(CONFIG_SND_SOC_TASDEVICE) += snd-soc-tasdevice.o
